ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.priceoracle]
path = "out/TrapPriceOracle.sol/TrapPriceOracle.json"
response_contract = "0x61f71401bdbe8c83a7a847ce345d156f4134d7a6"
response_function = "oracleRespond(string)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = []
address = 